-- ============================================================
-- SOJA - Rate Limiting & Enhanced Security
-- Run in Supabase SQL Editor after security_hardening.sql
-- ============================================================

-- ------------------------------------------------------------
-- 1) Rate limiting for anonymous orders
-- Prevent order spam from same IP
-- ------------------------------------------------------------

-- Create rate limit tracking table (optional - for monitoring)
create table if not exists public.order_rate_limits (
    id bigint generated by default as identity primary key,
    ip_address text not null,
    order_count int default 0,
    window_start timestamp with time zone default now(),
    created_at timestamp with time zone default now()
);

-- Index for efficient lookups
create index if not exists idx_order_rate_limits_ip 
on public.order_rate_limits (ip_address, window_start);

-- Function to check and increment rate limit
create or replace function public.check_order_rate_limit(request_ip inet)
returns boolean
language plpgsql
security definer
as $$
declare
    limit_count int := 10;  -- Max orders per window
    window_minutes int := 60;  -- Window in minutes
    current_count int;
begin
    -- Clean old entries
    delete from public.order_rate_limits 
    where window_start < now() - (window_minutes || ' minutes')::interval;

    -- Count orders in current window
    select coalesce(sum(order_count), 0) into current_count
    from public.order_rate_limits
    where ip_address = request_ip::text
      and window_start > now() - (window_minutes || ' minutes')::interval;

    if current_count >= limit_count then
        return false;  -- Rate limited
    end if;

    -- Increment counter (or insert if not exists)
    update public.order_rate_limits
    set order_count = order_count + 1,
        window_start = now()
    where ip_address = request_ip::text
      and window_start > now() - (window_minutes || ' minutes')::interval;

    if not found then
        insert into public.order_rate_limits (ip_address, order_count)
        values (request_ip::text, 1);
    end if;

    return true;
end;
$$;

-- ------------------------------------------------------------
-- 2) Enhanced order validation
-- Add phone format validation and other checks
-- ------------------------------------------------------------

create or replace function public.validate_order_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    -- Validate phone number format (Honduran format)
    -- Accepts: +504XXXXXXXX (12 chars) or 504XXXXXXXX (11 digits) or XXXXXXXX (8 digits)
    if new.client_phone is not null then
        if new.client_phone !~ '^\+504[0-9]{8}$'
           and new.client_phone !~ '^504[0-9]{8}$'
           and new.client_phone !~ '^[0-9]{8}$' then
            raise exception 'Invalid phone number format';
        end if;
    end if;

    -- Validate client name
    if new.client_name is not null and length(trim(new.client_name)) < 2 then
        raise exception 'Client name too short';
    end if;

    -- Validate total is not negative
    if new.total < 0 then
        raise exception 'Total cannot be negative';
    end if;

    return new;
end;
$$;

-- Apply the validation trigger
drop trigger if exists trg_validate_order_fields on public.orders;
create trigger trg_validate_order_fields
before insert or update on public.orders
for each row execute function public.validate_order_fields();

-- ------------------------------------------------------------
-- 3) Phone normalization function
-- Store normalized phone numbers
-- ------------------------------------------------------------

create or replace function public.normalize_honduran_phone(phone text)
returns text
language plpgsql
immutable
as $$
declare
    digits text;
begin
    if phone is null then
        return null;
    end if;

    -- Keep only digits
    digits := regexp_replace(phone, '[^0-9]', '', 'g');

    -- If 8 digits, assume local and add 504
    if length(digits) = 8 then
        return '504' || digits;
    end if;

    -- If 9 digits starting with 9, assume mobile without country
    if length(digits) = 9 and substr(digits, 1, 1) = '9' then
        return '504' || substr(digits, 2);
    end if;

    -- Return as-is if already 10 digits
    return digits;
end;
$$;

-- ------------------------------------------------------------
-- 4) Anonymize old orders for GDPR compliance
-- ------------------------------------------------------------

create or replace function public.anonymize_old_orders()
returns void
language plpgsql
security definer
as $$
begin
    -- Anonymize orders older than 90 days
    update public.orders
    set 
        client_name = 'Cliente Anonimizado',
        client_phone = NULL,
        location = NULL,
        observations = NULL
    where created_at < now() - interval '90 days'
      and client_phone is not null;
end;
$$;

-- ------------------------------------------------------------
-- 5) Security: Log suspicious activity
-- ------------------------------------------------------------

create table if not exists public.security_logs (
    id bigint generated by default as identity primary key,
    event_type text not null,
    user_id uuid,
    ip_address inet,
    details jsonb,
    created_at timestamp with time zone default now()
);

create index if not EXISTS idx_security_logs_created 
on public.security_logs (created_at DESC);

-- Function to log security events
create or replace function public.log_security_event(
    event_type text,
    user_id_param uuid,
    ip_address_param inet,
    details_param jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
as $$
begin
    insert into public.security_logs (event_type, user_id, ip_address, details)
    values (event_type, user_id_param, ip_address_param, details_param);
end;
$$;

-- Grant execute to authenticated users
grant execute on function public.check_order_rate_limit(inet) to anon, authenticated;
grant execute on function public.validate_order_fields() to anon, authenticated;
grant execute on function public.normalize_honduran_phone(text) to anon, authenticated;
grant execute on function public.anonymize_old_orders() to service_role;
grant execute on function public.log_security_event(text, uuid, inet, jsonb) to anon, authenticated;
